import * as core from '@actions/core'
import * as github from '@actions/github'
import { parseAlert } from './parsers'
import { buildPrompt } from './prompt'
import { createIssue, commentOnIssue, createPR, linkPRToIssue } from './clients/github'
import { updateIncident, formatIncidentNote } from './clients/pagerduty'
import { findDuplicates } from './dedup'
import { loadConfig } from './config'
import { runClaudeCode, meetsConfidenceThreshold } from './claude'
import {
  configureGit,
  createFixBranch,
  stageChanges,
  commitChanges,
  pushBranch,
  getDefaultBranch,
  discardChanges
} from './git'
import type { ActionInputs, ActionResult, Alert, Config } from './types'

/**
 * Get action inputs from environment
 */
function getInputs(): ActionInputs {
  return {
    anthropicApiKey: core.getInput('anthropic_api_key', { required: true }),
    alertPayload: core.getInput('alert_payload', { required: true }),
    alertSource: core.getInput('alert_source') || 'auto',
    mode: (core.getInput('mode') || 'auto') as ActionInputs['mode'],
    createIssue: core.getInput('create_issue') !== 'false',
    pagerdutyApiKey: core.getInput('pagerduty_api_key') || undefined,
    confidenceThreshold: (core.getInput('confidence_threshold') || 'medium') as ActionInputs['confidenceThreshold'],
    timeoutMinutes: parseInt(core.getInput('timeout_minutes') || '10', 10),
    maxFilesChanged: parseInt(core.getInput('max_files_changed') || '10', 10)
  }
}

/**
 * Format issue body from alert
 */
function formatIssueBody(alert: Alert): string {
  let body = `## Alert Details

| Field | Value |
|-------|-------|
| Source | ${alert.source} |
| Severity | ${alert.severity} |
| Service | ${alert.service || 'N/A'} |
| Time | ${alert.timestamp} |
${alert.url ? `| Link | [View in ${alert.source}](${alert.url}) |` : ''}

## Description

${alert.description}
`

  if (alert.stackTrace) {
    body += `
## Stack Trace

\`\`\`
${alert.stackTrace}
\`\`\`
`
  }

  if (alert.tags && Object.keys(alert.tags).length > 0) {
    body += `
## Tags

${Object.entries(alert.tags).map(([k, v]) => `- **${k}**: ${v}`).join('\n')}
`
  }

  body += `
---
*This issue was created automatically by [oncall-agent](https://github.com/vignesh07/oncall-agent)*
`

  return body
}

/**
 * Format PR body
 */
function formatPRBody(alert: Alert, analysis: string, confidence: string, issueNumber?: number): string {
  let body = `## Automated Fix for Alert

This PR was automatically generated by oncall-agent in response to a production alert.

### Alert Details

| Field | Value |
|-------|-------|
| Source | ${alert.source} |
| Title | ${alert.title} |
| Severity | ${alert.severity} |
| Service | ${alert.service || 'N/A'} |
${alert.url ? `| Link | [View in ${alert.source}](${alert.url}) |` : ''}

### Analysis

${analysis}

### Confidence: ${confidence}

---

⚠️ **Please review carefully before merging.**

This fix was generated automatically. While the analysis suggests this is a valid fix, please:
1. Review all changed files
2. Ensure tests pass
3. Verify the fix addresses the root cause
4. Consider any edge cases

`

  if (issueNumber) {
    body += `\nCloses #${issueNumber}\n`
  }

  body += `\n---\n*Generated by [oncall-agent](https://github.com/vignesh07/oncall-agent)*`

  return body
}

/**
 * Format analysis comment for issue
 */
function formatAnalysisComment(analysis: string, confidence: string, hasChanges: boolean): string {
  let comment = `## 🤖 oncall-agent Analysis

`

  if (!hasChanges) {
    comment += `I investigated this alert but did not find a code fix I'm confident in.

### What I Found

${analysis}

### Confidence: ${confidence}

### Recommended Next Steps

- Review the analysis above
- Check related logs and metrics
- Consider whether this requires infrastructure changes
- Manual investigation may be needed

`
  } else {
    comment += `I analyzed this alert and found a potential fix.

### Analysis

${analysis}

### Confidence: ${confidence}

`
  }

  comment += `---
*This analysis was generated automatically by [oncall-agent](https://github.com/vignesh07/oncall-agent). Please verify before taking action.*`

  return comment
}

/**
 * Main action entry point
 */
async function run(): Promise<void> {
  let result: ActionResult = {
    actionTaken: 'error',
    analysis: '',
    confidence: 'low'
  }

  try {
    const inputs = getInputs()
    core.info('oncall-agent starting...')

    // Parse the alert payload
    let payload: unknown
    try {
      payload = JSON.parse(inputs.alertPayload)
    } catch {
      throw new Error('Failed to parse alert_payload as JSON')
    }

    const alert = parseAlert(payload, inputs.alertSource)
    core.info(`Parsed alert: "${alert.title}" from ${alert.source} (severity: ${alert.severity})`)

    // Load repository config
    const config = await loadConfig()

    // Get GitHub token and create octokit
    const githubToken = process.env.GITHUB_TOKEN
    if (!githubToken) {
      throw new Error('GITHUB_TOKEN environment variable is required')
    }
    const octokit = github.getOctokit(githubToken)

    // Check for duplicates
    const duplicates = await findDuplicates(alert, octokit, config)

    if (duplicates.length > 0) {
      const dup = duplicates[0]
      core.info(`Found duplicate issue #${dup.number} (similarity: ${(dup.similarity * 100).toFixed(0)}%)`)

      // Comment on existing issue
      await commentOnIssue(
        octokit,
        dup.number,
        `🔔 **New alert received** that appears related to this issue:\n\n**${alert.title}**\n\n${alert.description}`
      )

      result = {
        actionTaken: 'duplicate',
        issueNumber: dup.number,
        duplicateOf: dup.number,
        analysis: `Duplicate of issue #${dup.number}`,
        confidence: 'high'
      }

      setOutputs(result)
      return
    }

    // Create tracking issue if enabled
    let issueNumber: number | undefined
    if (inputs.createIssue) {
      const labels = ['oncall-agent', alert.severity]
      if (alert.service) {
        labels.push(`service:${alert.service}`)
      }

      issueNumber = await createIssue(octokit, {
        title: `[${alert.source}] ${alert.title}`,
        body: formatIssueBody(alert),
        labels
      })
      core.info(`Created tracking issue #${issueNumber}`)
    }

    // Build prompt for Claude
    const prompt = buildPrompt(alert, config)
    core.info(`Built prompt (${prompt.length} chars)`)

    // Determine mode
    const shouldAttemptFix = inputs.mode === 'pr' || inputs.mode === 'auto'

    // Run Claude Code
    core.info('Running Claude Code analysis...')
    const claudeResult = await runClaudeCode(prompt, {
      timeoutMinutes: inputs.timeoutMinutes,
      maxFilesChanged: inputs.maxFilesChanged
    })

    core.info(`Claude finished. Success: ${claudeResult.success}, Has changes: ${claudeResult.hasChanges}, Confidence: ${claudeResult.confidence}`)

    // Determine what action to take
    const shouldCreatePR =
      shouldAttemptFix &&
      claudeResult.success &&
      claudeResult.hasChanges &&
      meetsConfidenceThreshold(claudeResult.confidence, inputs.confidenceThreshold)

    if (shouldCreatePR) {
      core.info('Creating PR with fix...')

      // Configure git for CI
      await configureGit()

      // Create branch
      const branchName = await createFixBranch(alert.id)
      core.info(`Created branch: ${branchName}`)

      // Stage and commit changes
      const changedFiles = await stageChanges()
      core.info(`Staged ${changedFiles.length} files: ${changedFiles.join(', ')}`)

      const committed = await commitChanges(alert.title, alert.source)
      if (!committed) {
        throw new Error('Failed to commit changes')
      }

      // Push branch
      await pushBranch(branchName)
      core.info('Pushed branch to remote')

      // Create PR
      const defaultBranch = await getDefaultBranch()
      const prNumber = await createPR(octokit, {
        title: `fix: ${alert.title}`,
        body: formatPRBody(alert, claudeResult.analysis, claudeResult.confidence, issueNumber),
        head: branchName,
        base: defaultBranch,
        draft: true,
        labels: ['oncall-agent', 'automated-fix']
      })
      core.info(`Created PR #${prNumber}`)

      // Link PR to issue
      if (issueNumber) {
        await linkPRToIssue(octokit, prNumber, issueNumber)
      }

      result = {
        actionTaken: 'pr_created',
        issueNumber,
        prNumber,
        analysis: claudeResult.analysis,
        confidence: claudeResult.confidence
      }

    } else {
      // Just post analysis
      core.info('Posting analysis (no PR created)')

      // Discard any changes Claude made
      if (claudeResult.hasChanges) {
        await discardChanges()
      }

      // Post analysis to issue
      if (issueNumber) {
        await commentOnIssue(
          octokit,
          issueNumber,
          formatAnalysisComment(claudeResult.analysis, claudeResult.confidence, claudeResult.hasChanges)
        )
      }

      result = {
        actionTaken: 'analysis_only',
        issueNumber,
        analysis: claudeResult.analysis,
        confidence: claudeResult.confidence
      }

      if (!claudeResult.success) {
        result.error = claudeResult.error
      }
    }

    // Update PagerDuty if configured
    if (inputs.pagerdutyApiKey && alert.source === 'pagerduty') {
      try {
        const note = formatIncidentNote(
          result.actionTaken,
          result.analysis,
          result.confidence,
          result.prNumber,
          result.issueNumber
        )
        await updateIncident(inputs.pagerdutyApiKey, alert.id, { note })
        core.info('Updated PagerDuty incident')
      } catch (error) {
        core.warning(`Failed to update PagerDuty: ${error}`)
      }
    }

    setOutputs(result)
    core.info(`Action completed: ${result.actionTaken}`)

  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    core.setFailed(`oncall-agent failed: ${message}`)

    result = {
      actionTaken: 'error',
      analysis: message,
      confidence: 'low',
      error: message
    }
    setOutputs(result)
  }
}

/**
 * Set all action outputs
 */
function setOutputs(result: ActionResult): void {
  core.setOutput('action_taken', result.actionTaken)
  core.setOutput('analysis', result.analysis)
  core.setOutput('confidence', result.confidence)

  if (result.issueNumber) {
    core.setOutput('issue_number', result.issueNumber)
  }
  if (result.prNumber) {
    core.setOutput('pr_number', result.prNumber)
  }
  if (result.duplicateOf) {
    core.setOutput('duplicate_of', result.duplicateOf)
  }
}

run()
